openapi: "3.0.3"
info:
  title: Open Library Search API
  description: |
    The Open Library Search API provides data about books.
    It allows retrieving Work and Edition level information about books,
    including author details, publication years, cover images, availability, and more.
  version: "1.0.0"
servers:
  - url: https://openlibrary.org
paths:
  /search.json:
    get:
      summary: Search for books
      operationId: searchBooks
      parameters:
        - name: q
          in: query
          description: The search query for books (e.g., book title, author, keywords).
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: |
            The fields to return from the search. Use "*" to return all fields.
            To fetch availability data, use "availability". Example: fields=*,availability.
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: |
            Sort the results by facets such as "new", "old", or "random".
            Default is by relevance.
          required: false
          schema:
            type: string
        - name: lang
          in: query
          description: |
            The two-letter ISO 639-1 language code. Influences the displayed language of
            results but doesn't exclude other language matches.
          required: false
          schema:
            type: string
        - name: offset
          in: query
          description: The offset for pagination (alternative to page).
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: The page number for pagination (starting from 1).
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: The number of results to return per page. Default is 10.
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response with a list of books and related metadata.
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_found:
                    type: integer
                    description: The total number of books found.
                  start:
                    type: integer
                    description: The starting index of the results.
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
        '400':
          description: Bad request, invalid query parameters.
        '500':
          description: Internal server error.
  /search/authors.json:
    get:
      summary: Search for authors
      operationId: searchAuthors
      parameters:
        - name: q
          in: query
          description: The search query for authors (e.g., author name).
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with a list of authors and related metadata.
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_found:
                    type: integer
                    description: The total number of authors found.
                  start:
                    type: integer
                    description: The starting index of the results.
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Author'
        '400':
          description: Bad request, invalid query parameters.
        '500':
          description: Internal server error.

components:
  schemas:
    Book:
      type: object
      properties:
        cover_i:
          type: integer
          nullable: true
          description: ID of the cover image.
        has_fulltext:
          type: boolean
          description: Indicates if the book has full-text available.
        edition_count:
          type: integer
          description: The total number of editions of the book.
        title:
          type: string
          description: The title of the book.
        author_name:
          type: array
          items:
            type: string
          description: List of authors' names.
        first_publish_year:
          type: integer
          description: The year the book was first published.
        key:
          type: string
          description: The unique key identifier for the work.
        ia:
          type: array
          items:
            type: string
          description: Internet Archive identifiers for the book's editions.
        author_key:
          type: array
          items:
            type: string
          description: The unique key identifiers for the authors.
        public_scan_b:
          type: boolean
          description: Whether the book is available for public scanning.

    Author:
      type: object
      properties:
        key:
          type: string
          description: The unique identifier for the author.
        name:
          type: string
          description: The author's full name.
        birth_date:
          type: string
          description: The birth date of the author.
        death_date:
          type: string
          nullable: true
          description: The death date of the author, if applicable.
